### ISSUE TITLE
Something weird is happening on tablet on info page

### ISSUE THREAD

**Issue by klmolloy** [voxmedia/pixelpunch#13]
for some reason you can scroll, even though it doesn't look like it. Nexus 7 1st gen.

**Comment by allypalanzi** [comment]
@klmolloy screen shot?

**Comment by klmolloy** [comment]
![screenshot_2015-08-29-16-05-27](https://cloud.githubusercontent.com/assets/5619178/9564093/c68296dc-4e68-11e5-879f-3cef328c1c4c.png)
![screenshot_2015-08-29-16-05-39](https://cloud.githubusercontent.com/assets/5619178/9564094/c68ff0ac-4e68-11e5-9435-64bb0fe7c4ab.png)

Do these make sense? when you scroll, the frame stretches and shrinks....idk if any of this makes sense

**Comment by allypalanzi** [comment]
I _think_ this is because of the browser chrome, and not totally sure we can fix it :(

**Comment by allypalanzi** [comment]
woo fixed it
